### ISSUE TITLE
[Feat] Enhancement Form: Add functions for Forms

### ISSUE THREAD

**Issue by yash98012** [yash98012/NextJs_App#2]
Form on the platform, it has not functions. However, only static Form page. To enhance the usability and versatility of the platform, it is essential to implement the functionality for Form.
![image](https://github.com/yash98012/NextJs_App/assets/147434171/e3f71a35-650b-461a-b040-69fa96fdcde7)

Describe the solution i like
I would like to propose the implementation of the functionality for forms on the platform. These actions are pivotal for enhancing the user experience and facilitating efficient form management.

**Comment by sumit957602** [comment]
I want to work on it.
