### ISSUE TITLE
[feat] : Add list Forms Hook on the plateform

### ISSUE THREAD

**Issue by yash98012** [yash98012/NextJs_App#5]
Form on the platform, it has not list forms hook functions. To enhance the usability and versatility of the platform, it is essential to implement the functionality and list forms hook.

Describe the solution i like
I would like to propose the implementation of the functionality and add list forms hook for forms on the platform. These actions are pivotal for enhancing the user experience and facilitating efficient form management.

**Comment by sumit957602** [comment]
I want to work on it. Please assigned me

**Comment by praishere** [comment]
I started working on it.
