### ISSUE TITLE
[Bug] : Create form function not working

### ISSUE THREAD

**Issue by yash98012** [yash98012/NextJs_App#7]
Describe the bug
When clicked on create form icon then create form function does not working it shows
nothing.

To Reproduce
Go to 'http://app.localhost:3000/dashboard'
Click on Form
Click on create form button present
See error

Expected behavior
When clicked on create form ,the user should be able to create a form.

Screenshots/Videos
![image](https://github.com/yash98012/NextJs_App/assets/147434171/09c21481-2c9c-4a9f-a044-482a1352b073)

**Comment by praishere** [comment]
I have started working on it.
